# Generated by Django 2.1.5 on 2019-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('uname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('address1', models.CharField(max_length=70)),
                ('address2', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('zip', models.IntegerField(default=0)),
            ],
        ),
    ]
