# Generated by Django 2.1.5 on 2019-06-13 08:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190613_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartitem',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
