# Generated by Django 2.1.5 on 2019-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='product',
            name='field',
            field=models.CharField(choices=[('au', 'Automotive'), ('bb', 'Baby'), ('bt', 'Beauty & personal care'), ('bk', 'Books'), ('cm', 'Computers'), ('el', 'Electronics'), ('wm', "Women'fasion"), ('me', "Men'fasion"), ('gf', "Girls'fasion"), ('hk', 'Home & kitchen'), ('so', 'Sports & outdore'), ('tg', 'Toys & games')], default='cm', max_length=2),
        ),
    ]
