# Generated by Django 2.1.5 on 2019-06-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190611_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='field',
            field=models.CharField(choices=[('au', 'Automotive'), ('bb', 'Baby'), ('bt', 'Beauty & personal care'), ('bk', 'Books'), ('cm', 'Computers'), ('el', 'Electronics'), ('wm', "Women'fasion"), ('me', "Men'fasion"), ('hk', 'Home & kitchen'), ('so', 'Sports & outdore'), ('tg', 'Toys & games')], default='cm', max_length=2),
        ),
    ]
