# Generated by Django 2.1.5 on 2019-06-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190611_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='field',
            field=models.IntegerField(choices=[(1, 'Automotive'), (2, 'Baby'), (3, 'Beauty & personal care'), (4, 'Books'), (5, 'Computers'), (6, 'Electronics'), (7, "Women'fasion"), (8, "Men'fasion"), (9, 'Home & kitchen'), (10, 'Sports & outdore'), (11, 'Toys & games')], default=5),
        ),
    ]
