# Generated by Django 2.1.5 on 2019-06-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190611_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='field',
        ),
    ]
